# Generated by Django 5.2.2 on 2025-06-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=100)),
                ('config_value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'application_settings',
            },
        ),
    ]
